#!/usr/bin/env bash

# Set the key filename
key_filename="school"

# Set the number of bits for the key
key_bits=4096

# Set the passphrase
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f $key_filename -N "$passphrase"

# Display the information about the generated key pair
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $key_filename."
echo "Your public key has been saved in $key_filename.pub."
echo "The key fingerprint is:"
ssh-keygen -lf $key_filename
echo "The key's randomart image is:"
ssh-keygen -l -v -f $key_filename

# List the current directory
ls
