#!/usr/bin/env bash

# File: 2-ssh_config

# Host directive for your server
Host 172.17.0.15 
    # Use the private key
    IdentityFile ~/.ssh/school
    # Disable password authentication
    PasswordAuthentication no
