#!/usr/bin/env bash
# Bash script for transferring a file via SCP

# Checking for command line arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Disabling strict host key checking and transferring the file
scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Checking if the transfer was successful
if [ $? -eq 0 ]; then
    echo "FILE WAS TRANSFERRED SUCCESSFULLY"
else
    echo "FILE TRANSFER FAILED"
fi

