#!/usr/bin/env bash
# commands  to install nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow "nginx HTTP"

echo "Holberton School" | sudo tee /var/www/html/index.html
# testing nginx configuratioin
sudo nginx -t

sudo service nginx reload
