#!/usr/bin/env bash
# performing a 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/samkit4q permanent;"

sudo sed -i "server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
